### ISSUE TITLE
Map Display

### ISSUE THREAD

**Issue by GreyMatteOr** [Saturnd-Earth/se-fe#27]
Input: 
 - rings:   [...ringObjects...]
   -   ringObject:   { lat, long, innerDistance, outterDistance, title, color }
 - likes:   [...likeObjects...]
   -   likeObject: { lat, long, color} 
 - displayStats:   { width (in px), height (in px) }

- Expected output: a map object of given size with each `ring` displayed in the given color as well as each `like` dotted throughout. The map should be the dimensions given (don't worry about safeguarding a min or max size, that will be handled on our end)

IF IT SEEMS EASY (otherwise skip):
- A method to add a ring to the map without having to re-render the whole thing 
- A method to delete a ring

**Comment by MichaelEWalker87** [comment]
![Screen Shot 2021-01-07 at 3 53 53 PM](https://user-images.githubusercontent.com/54221369/103954059-9ebd7b80-5100-11eb-8024-2bb5f05a8925.png)

**Comment by GreyMatteOr** [comment]
Updated issue to include `like`s
