### ISSUE TITLE
Fix Make Post Tabs 

### ISSUE THREAD

**Issue by MichaelEWalker87** [Saturnd-Earth/se-fe#38]
- [ ]  The post tabs 

![Screen Shot 2021-01-11 at 2 23 20 PM](https://user-images.githubusercontent.com/54221369/104240008-9b840180-5418-11eb-9fb0-d335ecb43a3f.png)

- [ ] Add the functionality when clicking inside the input box

**Comment by GreyMatteOr** [comment]
Finished!
